# Generated by Django 4.2.28 on 2026-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_balancehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useractivities",
            name="amount",
            field=models.IntegerField(default=2500),
        ),
    ]
