# Generated by Django 4.2.28 on 2026-03-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_users_is_banned_alter_useractivities_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2026-02-07"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
