# Generated by Django 4.2.28 on 2026-03-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_users_created_at_users_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivities",
            name="region",
        ),
        migrations.AlterField(
            model_name="useractivities",
            name="amount",
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name="useractivities",
            name="status",
            field=models.CharField(
                choices=[
                    ("kutilmoqda", "Kutilmoqda"),
                    ("qabul qilindi", "Qabul qilindi"),
                    ("qabul qilinmadi", "Qabul qilinmadi"),
                    ("bajarilgan", "Bajarilgan"),
                ],
                default="kutilmoqda",
                max_length=20,
            ),
        ),
    ]
