# Generated by Django 4.2.28 on 2026-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_useractivities_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
