# Generated by Django 4.2.28 on 2026-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_users_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("Free", "free"),
                    ("Pro", "pro"),
                    ("Go", "go"),
                    ("Ultima", "ultima"),
                ],
                default="Free",
                max_length=10,
            ),
        ),
    ]
